networks:
  attendify_net:
    external: true

services:
  attendify_crm:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - attendify_net
    env_file:
      - .env
    