networks:
  attendify_net:
    driver: bridge



services:
  crm_consumers:
    build:
      context: .
      dockerfile: Dockerfile.consumers
    volumes:
      - .:/app
    networks:
      - attendify_net
    env_file:
      - .env

    
  crm_producers:
    build:
      context: .
      dockerfile: Dockerfile.producers
    volumes:
      - .:/app
    networks:
      - attendify_net
    env_file:
      - .env
