networks:
  attendify_net:
    driver: bridge



services:
  consumers:
    build:
      context: .
      dockerfile: Dockerfile.consumers
    command: node indexConsumers.js
    # ports:
    #   - "3000:3000"
    volumes:
      - .:/app
    networks:
      - attendify_net
    env_file:
      - .env

    
  producers:
    build:
      context: .
      dockerfile: Dockerfile.producers
    command: node indexProducers.js
    # ports:
    #   - "3001:3001"
    volumes:
      - .:/app
    networks:
      - attendify_net
    env_file:
      - .env
