name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Elke push naar main activeert de pipeline

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Repo code ophalen
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Docker installeren (standaard aanwezig op Ubuntu-latest)

    # 3️⃣ Inloggen bij Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

    # 5️⃣ Push naar Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
