name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Producers Image
      - name: Build Producers Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:latest \
            -f Dockerfile.producers .
          docker push ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:latest

      # Build & Push Consumers Image
      - name: Build Consumers Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:latest \
            -f Dockerfile.consumers .
          docker push ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:latest

      # Optional: Tag with Git commit hash
      - name: Get Git commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Tag Producers Image with Commit Hash
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:latest \
            ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:${{ env.COMMIT_HASH }}

      - name: Tag Consumers Image with Commit Hash
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:latest \
            ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:${{ env.COMMIT_HASH }}

      # Linting (optional)
      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint . --fix
      
      # Deploy naar server via SSH
      #- name: Deploy to Server via SSH
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.SSH_HOST }}
      #    username: ${{ secrets.SSH_USERNAME }}
      #    key: ${{ secrets.SSH_PRIVATE_KEY }}
      #    port: ${{ secrets.SSH_PORT || 22 }}
      #    script: |
      #      docker pull ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:latest
      #      docker pull ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:latest
      #      docker stop producers || true && docker rm producers || true
      #      docker stop consumers || true && docker rm consumers || true
      #      docker run -d --name producers ${{ secrets.DOCKER_USERNAME }}/attendify_crm-producers:latest
      #      docker run -d --name consumers ${{ secrets.DOCKER_USERNAME }}/attendify_crm-consumers:latest